#!/usr/bin/env python3
import json, subprocess, pathlib, hashlib, sys
BASE=pathlib.Path('/mnt/data/invchain')
ROOT=(BASE/'te016'/'truth-engine-v2_2.10.6-R3P1_CANONICAL').resolve()
PACK=(BASE/'TRUTH_ENGINE_2.10.6_R3P1_CANONICAL(1).zip').resolve()
RS=ROOT/'tools/runtime/run_state.py'; RB=BASE/'runtime_batch.py'
RUN_ID='20260911-1042-arab-spring-mechanisms'; AS_OF='2026-09-11'; SLUG='arab-spring-mechanisms'
RUN_DIR=ROOT/'investigations'/'2026-09'/f'2026-09-11_{SLUG}'
STATE=RUN_DIR/f'2026-09-11_10-42_{SLUG}_RUN_STATE.json'
CARD=BASE/'INV-016_RUN_CARD.md'

def run(cmd,check=True):
 p=subprocess.run(cmd,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
 if p.stdout.strip(): print(p.stdout.strip())
 if p.stderr.strip(): print(p.stderr.strip(),file=sys.stderr)
 if check and p.returncode: raise SystemExit(p.returncode)
 return p

def sha(p): return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def j(x): return json.dumps(x,ensure_ascii=False,separators=(',',':'))

run([sys.executable,str(RB),'check-pack','--pack',str(PACK),'--engine-root',str(ROOT)])
run([sys.executable,str(RS),'init','--state',str(STATE),'--run-id',RUN_ID,'--parent-run-id','NONE','--as-of',AS_OF,'--input-kind','RUN_CARD','--mission-mode','GREENFIELD','--input-ref','PATH:'+str(CARD),'--subject-slug',SLUG,'--truth-engine-root',str(ROOT),'--next-action','SCOPE','--complexity','HIGH','--complexity-score','9','--force'])
run([sys.executable,str(RS),'archive-input','--state',str(STATE),'--source-file',str(CARD)])
run([sys.executable,str(RS),'record-sys','--state',str(STATE),'--result','UNAVAILABLE','--tool','mnemolite','--ref','-','--call','MNEMO_Q'])
checked='2026-09-11T08:42:00+00:00'
sources=[
('A','◈','https://www.gao.gov/products/gao-09-993','U.S. GAO — Democracy Assistance (2009)','GAO-09-993','2009-09-28','highlights/full report'),
('A','◈','https://www.gao.gov/products/gao-14-799','U.S. GAO — Lessons Learned from Egypt','GAO-14-799','2014-07-24','highlights'),
('B','◉','https://academic.oup.com/joc/article-abstract/62/2/363/4085823','Tufekci & Wilson — Tahrir protest participation','JOC-2012-TUFEKCI-WILSON','2012-03-06','abstract/results'),
('C','◉','https://archive-yaleglobal.yale.edu/content/revolution-u','YaleGlobal — Revolution U','YALEGLOBAL-REVOLUTION-U','2011-02-24','April 6/CANVAS account'),
('C','◉','https://www.pbs.org/wgbh/pages/frontline/revolution-in-cairo/inside-april6-movement/','PBS FRONTLINE — Inside April 6 Movement','PBS-FRONTLINE-APRIL6','2011','movement chronology'),
('D','◈','https://wikileaks.org/plusd/cables/08CAIRO2572_a.html','U.S. diplomatic cable 08CAIRO2572','08CAIRO2572','2008-12-30','summary/comment'),
('other:iri','◉','https://www.iri.org/news/new-york-times-discusses-iris-support-for-democracy-groups-in-egypt/','IRI republication — U.S. Groups Helped Nurture Arab Uprisings','IRI-NYT-2011','2011-04-14','reported training/funding'),
('E','◉','https://journals.sagepub.com/doi/full/10.1089/cyber.2011.0177','Marzouki et al. — Facebook and Tunisian Revolution','CYBER-2012-TUNISIA','2012-04-23','abstract'),
('E','◉','https://academic.oup.com/book/8138/chapter-abstract/153623879','Breuer — Social Media in Tunisian Revolution','OUP-BREUER-2016','2016-08-18','abstract'),
('other:orbi','◉','https://orbi.uliege.be/handle/2268/178830','Lecomte — Révolution tunisienne et Internet','LECOMTE-2011','2011','abstract/full text metadata'),
('other:ned','◉','https://www.ned.org/publications-test-2/','NED — Annual reports index 2010–2012','NED-ANNUAL-INDEX','2012','2010/2011 annual report descriptions'),
]
cmds=[]
setrun={'parent_run_id':'NONE','complexity':'HIGH','complexity_score':9,'scope':'Cas sélectionnés 2010–2013 où les flux et actions sont documentables. Tracer acteur extérieur -> ressource/formation/plateforme/diplomatie -> bénéficiaire ou audience -> action de mobilisation -> exposition/participation -> effet politique. Prioriser archives, programmes d’aide, données de plateformes, communications diplomatiques, chronologies et études causales. Gardes : soutien != déclenchement ; réseau social != révolution ; financement != contrôle ; simultanéité != coordination ; changement de régime != effet attribuable à un seul mécanisme.','resume_count':0,'route_overrides':[],'loaded_modules':['definitions/SYMBOLS.md','definitions/PATTERNS.md','definitions/THREATS.md','forensic/GATES.md','forensic/REQUEST_LOG.md','clusters/POWER.md','clusters/NETWORK.md','clusters/INFORMATION.md','clusters/TEMPORAL.md'],'degraded_flags':['MNEMO_UNAVAILABLE']}
cmds += [{'cmd':'set-run','args':['--json',j(setrun)]},{'cmd':'memory-probe','args':['--status','NONE']}]
axes=[
 {'axis':'EXTERNAL_ASSISTANCE_TO_CAPACITY','question':'Quelles aides, formations ou contacts extérieurs ont créé une capacité organisationnelle documentable sans établir un commandement externe ?','sought_objects':['funding','training','contact','recipient','adoption','instruction'],'links':['CLM-001','CLM-002','CLM-003','CAU-001','CAU-002'],'attempt_ids':['QRY-001','QRY-002','QRY-004','QRY-005','QRY-006','QRY-007','QRY-011'],'result_ids':['FCT-001','FCT-002','FCT-005','FCT-006','FCT-007','FCT-008','FCT-012','FCT-013'],'status':'SATURATED'},
 {'axis':'PLATFORMS_TO_MOBILIZATION','question':'Les réseaux sociaux ont-ils modifié information, logistique et probabilité de participation, et avec quel niveau causal ?','sought_objects':['platform_use','information','logistics','participation','offline_action'],'links':['CLM-004','CLM-005','CAU-003','CAU-004'],'attempt_ids':['QRY-003','QRY-004','QRY-005','QRY-008','QRY-009','QRY-010'],'result_ids':['FCT-003','FCT-004','FCT-005','FCT-009','FCT-010','FCT-011'],'status':'SATURATED'},
 {'axis':'MOBILIZATION_TO_POLITICAL_OUTCOME','question':'Quelles preuves isolent l’effet marginal de l’aide extérieure ou des plateformes sur la chute du régime plutôt que sur la seule capacité ou participation ?','sought_objects':['counterfactual','outcome','repression','coalition','local_grievance','regime_response'],'links':['CLM-006','CAU-004','CAU-005'],'attempt_ids':['QRY-002','QRY-003','QRY-004','QRY-008','QRY-009','QRY-010'],'result_ids':['FCT-003','FCT-005','FCT-008','FCT-009','FCT-010','FCT-011','FCT-012'],'status':'SATURATED'}]
for a in axes: cmds.append({'cmd':'record-object','args':['--kind','AXS','--json',j(a)]})
cmds.append({'cmd':'checkpoint','args':['--label','SCOPE','--last-completed','7','--next-action','SEARCH']})
for i,(fam,role,url,title,cid,pub,loc) in enumerate(sources,1):
 cmds.append({'cmd':'record-query','args':['--mode','FETCH','--result','ACCEPTED','--url',url,'--query',f'INV-016 source fetch {i}','--accept-source','--role',role,'--family',fam,'--title',title,'--canonical-id',cid,'--publication-date',pub,'--checked-at',checked,'--locator',loc]})
cmds.append({'cmd':'checkpoint','args':['--label','SEARCH','--last-completed','9','--next-action','FACTS']})
facts=[
('https://www.gao.gov/products/gao-09-993','SRC-001','2009-09-28','U.S. democracy assistance in Egypt before 2011','GAO reports about $154.8 million in governance/justice/democracy funding allocated to Egypt over FY2006-2008, placing Egypt among the larger recipients outside Iraq/Afghanistan.'),
('https://www.gao.gov/products/gao-09-993','SRC-001','2009-09-28','Content of U.S. democracy assistance','U.S. democracy assistance programs included civic participation, civil-society strengthening, media freedom/freedom of information and related governance activities; funding was implemented through USAID, State DRL and NED structures.'),
('https://academic.oup.com/joc/article-abstract/62/2/363/4085823','SRC-003','2012-03-06','Egypt social media and first-day protest participation','A survey of Tahrir participants found that, controlling for other factors, social-media use greatly increased the odds a respondent attended protests on the first day; information was primarily interpersonal via Facebook, phone or face-to-face contact.'),
('https://academic.oup.com/joc/article-abstract/62/2/363/4085823','SRC-003','2012-03-06','Egypt protest media production','About half of surveyed Tahrir participants produced and disseminated visual material from demonstrations, mainly through Facebook, documenting an information/amplification function distinct from regime-change causality.'),
('https://archive-yaleglobal.yale.edu/content/revolution-u','SRC-004,SRC-005','2011-02-24','2008 Facebook mobilization negative control','The April 6 Facebook page rapidly accumulated roughly 70,000 followers in 2008, yet planned solidarity protests largely fizzled outside Mahalla under repression and organizational uncertainty, showing online reach was not sufficient for successful street mobilization.'),
('https://archive-yaleglobal.yale.edu/content/revolution-u','SRC-004,SRC-005','2011-02-24','CANVAS tactical training transfer','April 6 activist Mohamed Adel traveled to Serbia in 2009 and received training in nonviolent organization and street-mobilization tactics associated with CANVAS/Otpor, then returned to Egypt and trained others.'),
('https://www.iri.org/news/new-york-times-discusses-iris-support-for-democracy-groups-in-egypt/','SRC-007','2011-04-14','Reported U.S.-financed democracy training links','A contemporaneous report republished by IRI stated that Arab activists, including figures linked to Egypt’s April 6 movement, had received training or support from U.S.-financed democracy organizations; this establishes a reported support network, not an authenticated command chain.'),
('https://wikileaks.org/plusd/cables/08CAIRO2572_a.html','SRC-006','2008-12-30','April 6 activist contact with U.S. officials','A 2008 U.S. diplomatic cable records an April 6 activist’s participation in an Alliance of Youth Movements summit and meetings with U.S. officials and think tanks; the embassy explicitly expressed doubt about his claim of a coordinated opposition transition plan.'),
('https://journals.sagepub.com/doi/full/10.1089/cyber.2011.0177','SRC-008','2012-04-23','Tunisia Facebook perceived catalyst','A post-revolution online survey of 333 Tunisian Internet users identified political, informational and media-platform functions through which respondents perceived Facebook as a catalyst in the revolution.'),
('https://academic.oup.com/book/8138/chapter-abstract/153623879','SRC-009','2016-08-18','Tunisia social media coalition mechanisms','Research using expert interviews and a web survey of 608 Tunisian Facebook users argues that social media helped build networks, circumvent the media blackout, mitigate collective-action problems and support a national protest identity.'),
('https://orbi.uliege.be/handle/2268/178830','SRC-010','2011','Tunisia e-revolution caution','Lecomte describes Internet/social-media use as a catalyst for a protest movement born in Sidi Bouzid while warning against the e-revolution narrative that treats social networks as the triggering cause.'),
('https://www.gao.gov/products/gao-14-799','SRC-002','2014-07-24','Post-2011 U.S. democracy assistance and NGO trial','GAO found that Egypt’s prosecution of four U.S. NGOs significantly disrupted U.S. democracy-and-governance assistance after 2011; the U.S. government provided diplomatic, legal and grant-flexibility support, demonstrating an assistance infrastructure without proving orchestration of the 2011 uprising.'),
('https://www.ned.org/publications-test-2/','SRC-011','2012','Temporal control on NED Arab Spring response','NED describes responding to the Arab Spring as a priority in 2011 and continued a broad global grants program; post-uprising expansion or response cannot by itself be back-projected as evidence of pre-uprising tasking.')]
for url,srcs,date,subj,val in facts:
 cmds.append({'cmd':'record-fact','args':['--epi','FACT','--tier','✧','--url',url,'--sources',srcs,'--date',date,'--subject',subj,'--value',val,'--mem','-']})
cmds.append({'cmd':'assert-counts','args':['--json',j({'AXS':3})]})
cmds.append({'cmd':'checkpoint','args':['--label','FACTS','--last-completed','10','--next-action','CAUSAL']})
fstage={'schema':1,'stage':'facts','base_state_sha256':sha(STATE),'commands':cmds}
fp=BASE/'INV-016_FACTS_STAGE.json'; fp.write_text(json.dumps(fstage,ensure_ascii=False,indent=2),encoding='utf-8')
run([sys.executable,str(RB),'apply','--pack',str(PACK),'--engine-root',str(ROOT),'--state',str(STATE),'--stage-file',str(fp)])

claims=[
 {'claim':'Une infrastructure substantielle d’assistance démocratique américaine existait en Égypte avant 2011 et finançait des capacités de société civile, participation et médias.','claimant':'INV-016','materiality':'IMPORTANT','support':['FCT-001','FCT-002'],'counter':'NONE_FOUND','gap_type':'NONE','gap':'NONE','status':'SUPPORTED'},
 {'claim':'Un transfert tactique transnational de méthodes de mobilisation non violente vers au moins un militant d’April 6 est documenté avant 2011.','claimant':'INV-016','materiality':'DECISIVE','support':['FCT-006'],'counter':'NONE_FOUND','gap_type':'NONE','gap':'NONE','status':'SUPPORTED'},
 {'claim':'L’assistance occidentale documentée établit que les États-Unis ont commandé ou orchestré le soulèvement égyptien de janvier 2011.','claimant':'hypothèse forte','materiality':'DECISIVE','support':['FCT-001','FCT-002','FCT-007','FCT-008'],'counter':['FCT-008','FCT-012','FCT-013'],'gap_type':'CAUSALITY','gap':'Aucune instruction authentifiée reliant un financeur/État à la décision de lancer, au plan opérationnel ou à l’issue du soulèvement; le câble cité doute lui-même d’un plan coordonné.','status':'PARTIAL'},
 {'claim':'En Égypte, les réseaux sociaux ont facilité information, logistique et participation précoce aux manifestations.','claimant':'INV-016','materiality':'DECISIVE','support':['FCT-003','FCT-004'],'counter':['FCT-005'],'gap_type':'NONE','gap':'NONE','status':'SUPPORTED'},
 {'claim':'En Tunisie, Facebook et les réseaux sociaux ont contribué à l’information, aux réseaux et à la formation d’une coalition protestataire, sans être démontrés comme déclencheur unique.','claimant':'INV-016','materiality':'IMPORTANT','support':['FCT-009','FCT-010','FCT-011'],'counter':'NONE_FOUND','gap_type':'NONE','gap':'NONE','status':'SUPPORTED'},
 {'claim':'L’assistance extérieure ou les plateformes suffisent à expliquer causalement la chute des régimes lors des printemps arabes.','claimant':'hypothèse générale','materiality':'DECISIVE','support':['FCT-003','FCT-006','FCT-009','FCT-010'],'counter':['FCT-005','FCT-011','FCT-012'],'gap_type':'CAUSALITY','gap':'Les données ferment des mécanismes de capacité, diffusion et participation mais pas le contrefactuel de régime; répression, griefs locaux, coalitions et décisions des élites restent des causes concurrentes non isolées.','status':'PARTIAL'}]
causal=[
 {'mechanism':'assistance démocratique extérieure -> ressources/capacité de société civile','support':['FCT-001','FCT-002','FCT-012'],'counter':'Programmes multiples et bénéficiaires hétérogènes; capacité ne vaut pas instruction opérationnelle.','limit':'Capacité institutionnelle fermée, tasking non inféré.','causal_right':'financement/programmes -> capacités civiques/médiatiques/organisationnelles documentées','status':'SUPPORTED'},
 {'mechanism':'formation CANVAS -> apprentissage tactique -> transmission interne à April 6','support':['FCT-006'],'counter':['FCT-005'],'limit':'Transfert de méthode établi pour un acteur; effet marginal sur le soulèvement non isolé.','causal_right':'formation identifiée -> retour en Égypte -> enseignement de tactiques non violentes','status':'SUPPORTED'},
 {'mechanism':'usage réseaux sociaux -> information/logistique -> participation au premier jour en Égypte','support':['FCT-003','FCT-004'],'counter':['FCT-005'],'limit':'Association multivariée forte et mécanisme plausible; pas d’assignation randomisée ni effet sur issue du régime.','causal_right':'usage social media -> information/logistique -> probabilité accrue de participation initiale','status':'SUPPORTED'},
 {'mechanism':'réseaux sociaux -> coalition/mobilisation -> chute de régime en Tunisie','support':['FCT-009','FCT-010'],'counter':['FCT-011'],'gap_type':'CAUSALITY','gap':'Les études sont rétrospectives/perceptives et le mouvement naît localement à Sidi Bouzid; absence de contrefactuel sans réseaux sociaux.','limit':'Catalyse informationnelle/coalition soutenue; déclenchement et résultat non isolés.','status':'UNRESOLVED'},
 {'mechanism':'assistance extérieure + plateformes -> soulèvement -> changement de régime','support':['FCT-001','FCT-006','FCT-003','FCT-009'],'counter':['FCT-005','FCT-008','FCT-011','FCT-012'],'gap_type':'CAUSALITY','gap':'Pas de chaîne unique de commandement ni de design identifiant l’effet marginal sur la survie du régime.','limit':'Contributions intermédiaires documentées; causalité générale du changement de régime non établie.','status':'UNRESOLVED'}]
controls=[
 {'control':'audience numérique != mobilisation de rue réussie','support':['FCT-005'],'status':'PASS'},
 {'control':'contact/formation externe != tasking étatique','support':['FCT-006','FCT-008'],'status':'PASS'},
 {'control':'assistance démocratique != orchestration de révolution','support':['FCT-001','FCT-002','FCT-012'],'status':'PASS'},
 {'control':'réseau social != déclencheur unique','support':['FCT-011','FCT-005'],'status':'PASS'},
 {'control':'participation accrue != chute du régime attribuable','support':['FCT-003','FCT-010','FCT-011'],'status':'PASS'}]
sections={
'TEMPORAL_STATE':{'as_of':'2026-09-11','window':'Égypte/Tunisie principalement 2006-2013, avec études rétrospectives ultérieures','breaks':['2006-2008 assistance US préexistante','2008 April 6 mobilisation Facebook et échec partiel hors Mahalla','2009 formation CANVAS documentée','2010-2011 soulèvements Tunisie/Égypte','2012-2014 évaluations postérieures'],'status':'HISTORICAL_BOUNDED'},
'MANIPULATION_REPORT':{'input_kind':'RUN_CARD','mission_mode':'GREENFIELD','symbol_stage':'CORPUS_FINAL','symbols':{f'S{i:02d}':v for i,v in enumerate(['acteur extérieur','financement','formation','ONG','militant','plateforme','information','réseau','tactique','mobilisation','participation','répression','coalition','régime','effet'],1)},'patterns':{'P01':'assistance-to-capacity','P02':'training-to-adoption','P03':'platform-to-participation','P04':'participation-without-outcome-closure'},'threats':['support=trigger','funding=control','training=tasking','social media=revolution','participation=regime change','post-hoc aid=pre-event orchestration'],'rhetorical':{'R01':'transformer corrélation en commandement','R02':'réduire une coalition à un outil numérique','R03':'attribuer l’issue à un mécanisme intermédiaire'},'complexity':{'band':'HIGH','score':9},'clusters':['POWER','NETWORK','INFORMATION','TEMPORAL'],'implicit':{'I01':'transfert de capacité peut être réel sans principal commanditaire','I02':'outils numériques réduisent des coûts sans déterminer l’issue','I03':'chronologie distingue soutien préexistant et réponse post-soulèvement'},'speaker':{'goal':'tester les chaînes externes et numériques des printemps arabes','target':'séparer capacité, mobilisation et changement de régime','tone':'forensic'},'assumptions':['les montants d’aide prouvent une infrastructure mais pas un bénéficiaire particulier','les enquêtes de manifestants identifient participation/logistique mieux que l’issue du régime','les récits organisationnels et journalistiques sur formation exigent un plafond causal'],'priorities':['dater aide/formation','identifier bénéficiaire et adoption','mesurer participation','exiger contrefactuel pour issue'],'query_guidance':'archives publiques, documents de financement, câbles, études académiques; utiliser les récits militants comme preuve bornée de formation/adoption, pas de causalité générale'},
'MODULE_EXECUTION':[
 {'module':'clusters/POWER.md','trigger':'assistance/diplomatie/régime','reason':'séparer capacité, soutien et commandement','input_ids':['FCT-001','FCT-002','FCT-007','FCT-008','FCT-012'],'operations_applied':['traced assistance to capacity','tested command/tasking edge'],'result_ids':['CLM-001','CLM-003','CAU-001','CAU-005'],'negative_results':['no authenticated U.S. command chain to launch uprising'],'not_computable':['marginal regime-survival effect of assistance'],'gaps':['operational instructions/counterfactual'],'status':'DONE'},
 {'module':'clusters/NETWORK.md','trigger':'transnational tactical transfer','reason':'distinguish contact/training from coordination','input_ids':['FCT-006','FCT-007','FCT-008'],'operations_applied':['mapped trainer-trainee relation','separated adoption from principal-agent control'],'result_ids':['CLM-002','CAU-002'],'negative_results':['no network-wide tasking established'],'not_computable':['full diffusion denominator'],'gaps':['participant-level adoption records'],'status':'DONE'},
 {'module':'clusters/INFORMATION.md','trigger':'Facebook/social media participation','reason':'separate exposure, logistics, participation and outcome','input_ids':['FCT-003','FCT-004','FCT-005','FCT-009','FCT-010','FCT-011'],'operations_applied':['tested information/logistics edge','used 2008 failure as negative control'],'result_ids':['CLM-004','CLM-005','CAU-003','CAU-004'],'negative_results':['online reach not sufficient for street success'],'not_computable':['platform counterfactual for regime collapse'],'gaps':['randomized/platform outage causal design'],'status':'DONE'},
 {'module':'clusters/TEMPORAL.md','trigger':'pre/post uprising assistance claims','reason':'prevent post-event response from back-projection','input_ids':['FCT-001','FCT-012','FCT-013'],'operations_applied':['ordered pre-2011 aid, 2011 uprising, post-2011 program response'],'result_ids':['CLM-001','CLM-006','CAU-005'],'negative_results':['post-2011 support cannot prove pre-2011 orchestration'],'not_computable':['latent informal pre-event contacts beyond records'],'gaps':['dated actor-specific grants/instructions'],'status':'DONE'}],
'SCOPING_REPORT':{'included':['Egypt pre-2011 democracy assistance','April 6/CANVAS transfer','Egypt social-media participation','Tunisia social-media coalition/catalyst','post-2011 aid chronology as control'],'excluded':['Libya/Syria military intervention','generic geopolitics','all Arab countries','claims without actor/case chain'],'reason':'bounded cases with traceable resource/platform mechanisms and explicit controls'},
'CREDO':{'rule':'prove each edge separately: assistance -> capacity -> adoption -> mobilization -> political outcome','forbidden_shortcuts':['support=trigger','funding=control','training=tasking','social media=revolution','participation=outcome']},
'COGNITIVE_MAP':{'chain':['acteur extérieur','ressource/formation','bénéficiaire','adoption','plateforme/information','mobilisation','participation','réaction régime','issue'],'rival_models':['endogenous grievance','labor/social coalition','digital facilitation','external capacity support','external orchestration']},
'DIALECTICAL_MAP':{'thesis':'Assistance occidentale et réseaux transnationaux/numériques ont contribué matériellement aux soulèvements.','antithesis':'Les soulèvements partent de griefs et coalitions domestiques; outils et formations ne déterminent ni déclenchement ni issue.','synthesis':'Capacités externes, transfert tactique et facilitation numérique sont établis dans des cas bornés; aucune chaîne ne ferme une orchestration externe ou une causalité générale sur la chute des régimes.'},
'RESOURCE_FLOW_MAP':{'flows':['US democracy assistance -> civil-society/media capacities in Egypt','CANVAS/Otpor -> tactical training -> April 6 activist','platforms -> information/logistics/amplification'],'limits':['funding does not identify tasking','training does not identify command','platform use does not identify regime outcome']},
'ACTOR_NETWORK_MAP':[
 {'from':'USAID/State/NED ecosystem','relation':'democracy assistance','to':'Egypt civil-society/governance programs','support':['FCT-001','FCT-002']},
 {'from':'CANVAS/Otpor trainers','relation':'nonviolent tactics training','to':'Mohamed Adel / April 6','support':['FCT-006']},
 {'from':'Facebook/social media interpersonal networks','relation':'information/logistics','to':'Tahrir participants','support':['FCT-003','FCT-004']},
 {'from':'Tunisian digital networks','relation':'information/coalition facilitation','to':'protest ecosystem','support':['FCT-009','FCT-010','FCT-011']}],
'IMPACT_MAP':{'established':['pre-2011 democracy-assistance infrastructure in Egypt','CANVAS tactical transfer to at least one April 6 activist','social-media facilitation of first-day participation/logistics in Egypt','social-media catalytic/network role in Tunisia'],'partial':['extent of U.S.-financed training links to April 6 as an organization','marginal contribution of tactical training to mobilization'],'not_established':['U.S. command of January 25 uprising','social media as sole trigger','external assistance as sufficient cause of regime change']},
'CONTRADICTION_LEDGER':[
 {'issue':'reports of U.S.-financed training versus lack of authenticated tasking','resolution':'retain support-network fact; do not infer command or funding of the uprising'},
 {'issue':'large Facebook audience in 2008 but weak street result','resolution':'use as direct sufficiency control against online reach = mobilization'},
 {'issue':'Tunisia studies call Facebook catalyst while warning against e-revolution myth','resolution':'separate information/coalition mechanism from trigger/outcome causality'},
 {'issue':'post-2011 U.S./NED response may be mistaken for pre-event design','resolution':'enforce temporal ordering; post-event response cannot establish prior orchestration'}],
'VERIFICATION_REPORT':{'research_queries':11,'sources_fetched':11,'facts':13,'method':'official funding records + diplomatic archive + academic participation studies + bounded training accounts + explicit negative controls','negative_checks':['2008 April 6 Facebook mobilization fizzled outside Mahalla','embassy doubted claimed transition plan','Tunisia e-revolution caution','post-2011 assistance temporal control'],'verdict':'sufficient for capacity/training/platform facilitation; insufficient for external orchestration or general regime-change causality'},
'EDI_REPORT':{'source_counts':{'A':2,'B':1,'C':2,'D':1,'E':2,'other:iri':1,'other:orbi':1,'other:ned':1},'edi':'DIVERSE_OFFICIAL_ACADEMIC_ARCHIVAL_WITH_CONTESTED_SUPPORT_SEPARATED','dimensions':['funding','diplomatic contact','training transfer','platform participation','Tunisia coalition','temporal control'],'corpus':'11 accepted sources across 9 provenance families','decisive_claim_coverage':[{'claim':'CLM-001','families':['A']},{'claim':'CLM-002','families':['C']},{'claim':'CLM-003','families':['A','D','other:iri']},{'claim':'CLM-004','families':['B','C']},{'claim':'CLM-005','families':['E','other:orbi']},{'claim':'CLM-006','families':['A','B','C','E','other:orbi']}],'diagnostic_not_truth':True},
'RESPONSIBILITY_MAP':[
 {'actor':'U.S. democracy-assistance institutions','documented_action':'financed democracy/civil-society/media programs in Egypt before 2011','intent':'PROVEN','scope':'capacity support; uprising tasking not established','support':['FCT-001','FCT-002']},
 {'actor':'CANVAS/Otpor network','documented_action':'trained at least one April 6 activist in nonviolent organizing tactics','intent':'PROVEN','scope':'training transfer; regime-change causality not established','support':['FCT-006']},
 {'actor':'social-media networks','documented_action':'facilitated information/logistics and were associated with early protest participation','intent':'N/A','scope':'mechanism of communication/coordination, not intentional principal','support':['FCT-003','FCT-004','FCT-009','FCT-010']},
 {'actor':'domestic protest coalitions','documented_action':'converted grievances/networks into street mobilization under repression','intent':'PARTIAL','scope':'domestic causal structure incompletely measured here','support':['FCT-005','FCT-011']}],
'NEXT_QUERIES':['To close external orchestration, require authenticated instructions tying a funder/state to launch timing, operational plan and beneficiary compliance.','To estimate platform causal effect, seek exogenous outages or stronger quasi-experimental variation linked to protest participation and outcome.','For synthesis, retain capacity/training/platform mechanisms separately from trigger and regime-change claims.']}
cmds=[]
for o in claims: cmds.append({'cmd':'record-object','args':['--kind','CLM','--json',j(o)]})
for o in causal: cmds.append({'cmd':'record-object','args':['--kind','CAU','--json',j(o)]})
for o in controls: cmds.append({'cmd':'record-object','args':['--kind','CTRL','--json',j(o)]})
for name,val in sections.items(): cmds.append({'cmd':'set-section','args':['--name',name,'--json',j(val)]})
cmds += [
 {'cmd':'checkpoint','args':['--label','CAUSAL','--last-completed','11','--next-action','VERIFY']},
 {'cmd':'checkpoint','args':['--label','VERIFY','--last-completed','13','--next-action','INVESTIGATION_ACCOUNTABILITY']},
 {'cmd':'checkpoint','args':['--label','INVESTIGATION_ACCOUNTABILITY','--last-completed','17','--next-action','FINALIZE']},
 {'cmd':'assert-counts','args':['--json',j({'AXS':3,'CLM':6,'CAU':5,'CTRL':5})]},
 {'cmd':'set-gates','args':['--json',j({f'G{i}':'PASS' for i in range(11)})]},
 {'cmd':'mark-final','args':[]}]
tail={'schema':1,'stage':'tail','base_state_sha256':sha(STATE),'commands':cmds}
tp=BASE/'INV-016_TAIL_STAGE.json'; tp.write_text(json.dumps(tail,ensure_ascii=False,indent=2),encoding='utf-8')
run([sys.executable,str(RB),'apply','--pack',str(PACK),'--engine-root',str(ROOT),'--state',str(STATE),'--stage-file',str(tp)])
run([sys.executable,str(RS),'validate','--state',str(STATE),'--phase','pre'])
print('STATE='+str(STATE)); print('RUN_DIR='+str(RUN_DIR))
